fun main(){
    // Behebe die Exception
    var test: String = "78910"
    var test2: Int = test.toInt()
    println(test2)
}